version: '3.8'

services:
  promtail:
    container_name: promtail
    restart: unless-stopped
    image: grafana/promtail:latest
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml