global:
  scrape_interval: 15s
  
# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
        
rule_files:
  - "rules.yml"
   
scrape_configs:
  - job_name: "grafana"
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]
      
  - job_name: "alertmanager"
    metrics_path: /metrics
    static_configs:
      - targets: ["alertmanager:9093"]
      
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]
      
  - job_name: "loki"
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]
      
  #- job_name: "node_exporter"
  #  metrics_path: /metrics
  #  static_configs:
  #    - targets: ["node_exporter:9100"]

  - job_name: "livepeer"
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["PutYourOrchestartorIPOrDNSHere"]