apiVersion: 1

datasources:
- name: Prometheus
  access: proxy
  type: prometheus
  url: http://prometheus:9090
  isDefault: true

- name: loki
  access: proxy
  basicAuth: false
  editable: true
  type: loki
  uid: loki
  url: http://loki:3100
  version: 1
  
- name: JSON API
  access: proxy
  basicAuth: false
  editable: true
  type: marcusolsson-json-datasource
  uid: 7uw6x7O4z
  url: https://arb1.arbitrum.io/rpc
  version: 1
