global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: ERROR  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/traefik.log

# (Optional) Accesslog
# ---
accessLog:
  format: common  # common, json, logfmt
  filePath: /var/log/traefik/access.log

# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: true  # true by default
  insecure: false  # Don't do this in production! Use routers instead.

# Entry Points configuration
# ---
entryPoints:
  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
   production:
     acme:
       email: PutYourEmailHere
       storage: /etc/traefik/acme.json
       caServer: "https://acme-v02.api.letsencrypt.org/directory"
       tlsChallenge: {}
providers:
  docker:
    exposedByDefault: false  # Default is true
  file:
    directory: /etc/traefik
    watch: false
